### ISSUE TITLE
Unable to save file to google drive.  Write command results in an error. 

### ISSUE THREAD

**Issue by github-grabaz** [as247/flysystem-google-drive#2]
Trying to save local file to google drive but keep getting errors regarding the 3rd parameter config:

`Storage::disk('google')->write('test.txt', $localfile);`
and
`Storage::disk('google')->write('test.txt', $localfile, null);`
results in the following error:
`Argument 3 passed to As247\Flysystem\GoogleDrive\GoogleDriveAdapter::writeStream() must be an instance of League\Flysystem\Config, null given, called in I:\www\lendterra\vendor\as247\flysystem-drive-support\src\StorageToAdapter.php on line 48`

Suggestions?

**Comment by as247** [comment]
Hi, pls try this
`Storage::disk('google')->write('test.txt', $localfile, new \League\Flysystem\Config());`

**Comment by github-grabaz** [comment]
Good call - that worked.

I did try something similar but it had failed.  I know I wasn't as explicit in my call to Config().

Thanks!
